Fix sporadic error about broken pipe when checking recent SRs
This code sometimes runs into:

```
Exception ignored in: <osc.util.safewriter.SafeWriter object at 0x7fbe42c17860>
BrokenPipeError: [Errno 32] Broken pipe
Retrying up to 3 more times after sleeping 3s …
```

This is easily reproducible by adding the condition into a separate script
and running it a few times. The additional `cat > /dev/null` which this
change introduces seems to fix the issue.

Related ticket: https://progress.opensuse.org/issues/167395